package Excepciones;

public class Ej3 {
	
	public static void main(String args[]) {
		 Thrower t = new Thrower();
		 try {
		 t.g();
		 } catch(Ej2ex e) {
		 e.imprimirmensaje();
		 }
		 }
		}
	
	class Thrower {
		public void f() {
			// Compiler gives an error: "unreported
			// exception MyException; must be caught
			// or declared to be thrown"
			// ! throw new MyException("Inside f()");
		}

		public void g() throws Ej2ex {
			throw new Ej2ex("Inside g()");
		}
	}

}
